### ISSUE TITLE
java.io.IOException

### ISSUE THREAD

**Issue by srmcatee1110** [adyliu/jeos#4]
I get an EOF IO Exception.  I have looked around and what I see is the server is closing the connection and the client from jeos is not keeping it open.  

I have found one post in github that says to fix this add this to the http client connection.  
addHeader("Connection","close")

Problem is I'm not sure in jeos where I have access to the client to add this???

Here's the stack trace:
`Exception in thread "main" io.jafka.jeos.exception.EosApiException: java.io.IOException: unexpected end of stream on Connection{127.0.0.1:8888, proxy=DIRECT hostAddress=/127.0.0.1:8888 cipherSuite=none protocol=http/1.1}
	at io.jafka.jeos.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:64)
	at io.jafka.jeos.impl.EosApiRestClientImpl.abiJsonToBin(EosApiRestClientImpl.java:122)
	at Main.main(Main.java:69)
Caused by: java.io.IOException: unexpected end of stream on Connection{127.0.0.1:8888, proxy=DIRECT hostAddress=/127.0.0.1:8888 cipherSuite=none protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at io.jafka.jeos.impl.LoggingInterceptor.intercept(LoggingInterceptor.java:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
	at io.jafka.jeos.impl.EosApiServiceGenerator.executeSync(EosApiServiceGenerator.java:56)
	... 2 more
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 22 more

Process finished with exit code 1`

**Comment by srmcatee1110** [comment]
Error on my part.  Resolved and closing.
